### ISSUE TITLE
OSError: [Errno 48] Address already in use

### ISSUE THREAD

**Issue by nnnLik** [smartsenselab/sensecam-discovery#4]
I am using your library with Django and sending two requests to run sensecam_discovery.discover() I get an error

```
Traceback (most recent call last):
  File "/Users/macbook/Python-Proj/test/django/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/macbook/Python-Proj/test/django/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/macbook/Python-Proj/test/django/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/macbook/Python-Proj/test/django/venv/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/macbook/Python-Proj/test/django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/macbook/Python-Proj/test/django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/macbook/Python-Proj/test/django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/macbook/Python-Proj/test/django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/macbook/Python-Proj/test/django/apps/Locations/views.py", line 56, in list
    all_cameras_ips = sensecam_discovery.discover()
  File "/Users/macbook/Python-Proj/test/django/venv/lib/python3.9/site-packages/sensecam_discovery/Discover.py", line 24, in discover
    wsd.start()
  File "/Users/macbook/Python-Proj/test/django/venv/lib/python3.9/site-packages/wsdiscovery/threaded.py", line 285, in start
    self._startThreads()
  File "/Users/macbook/Python-Proj/test/django/venv/lib/python3.9/site-packages/wsdiscovery/threaded.py", line 265, in _startThreads
    self._networkingThread.start()
  File "/Users/macbook/Python-Proj/test/django/venv/lib/python3.9/site-packages/wsdiscovery/threaded.py", line 239, in start
    self._multiInSocket = self._createMulticastInSocket()
  File "/Users/macbook/Python-Proj/test/django/venv/lib/python3.9/site-packages/wsdiscovery/threaded.py", line 109, in _createMulticastInSocket
    sock.bind(('', MULTICAST_PORT))
OSError: [Errno 48] Address already in use
ERROR:django.request:Internal Server Error: /api/locations/get_all_cameras/
Traceback (most recent call last):
  File "/Users/macbook/Python-Proj/test/django/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/macbook/Python-Proj/test/django/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/macbook/Python-Proj/test/django/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/macbook/Python-Proj/test/django/venv/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/macbook/Python-Proj/test/django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/macbook/Python-Proj/test/django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/macbook/Python-Proj/test/django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/macbook/Python-Proj/test/django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/macbook/Python-Proj/test/django/apps/Locations/views.py", line 56, in list
    all_cameras_ips = sensecam_discovery.discover()
  File "/Users/macbook/Python-Proj/test/django/venv/lib/python3.9/site-packages/sensecam_discovery/Discover.py", line 24, in discover
    wsd.start()
  File "/Users/macbook/Python-Proj/test/django/venv/lib/python3.9/site-packages/wsdiscovery/threaded.py", line 285, in start
    self._startThreads()
  File "/Users/macbook/Python-Proj/test/django/venv/lib/python3.9/site-packages/wsdiscovery/threaded.py", line 265, in _startThreads
    self._networkingThread.start()
  File "/Users/macbook/Python-Proj/test/django/venv/lib/python3.9/site-packages/wsdiscovery/threaded.py", line 239, in start
    self._multiInSocket = self._createMulticastInSocket()
  File "/Users/macbook/Python-Proj/test/django/venv/lib/python3.9/site-packages/wsdiscovery/threaded.py", line 109, in _createMulticastInSocket
    sock.bind(('', MULTICAST_PORT))
OSError: [Errno 48] Address already in use
```

**Comment by nnnLik** [comment]
No matter what web framework I use, this error is everywhere

**Comment by nnnLik** [comment]
If you implement it through a class, there will be no errors
